export const GET_ALL_CHARACTERS = 'GET_ALL_CHARACTERS'
export const GET_ALL_LOCATION = 'GET_ALL_LOCATION'
export const GET_ALL_EPISODES = 'GET_ALL_CHARACTERS'
export const CHANGE_PAGINATION = 'CHANGE_PAGINATION'
